# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md
openapi: "3.0.3"
info:
  title: "JFM API specification"
  description: "An internal JSON API intended for JFM front-end system"
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.0.5"
servers:
  - url: "http://host:12222"
paths:
  /api/v1/transcribe:
    post:
      description: "Transcribe voice to text"
      operationId: "TranscribeVoiceToText"
      requestBody:
        description: "Provide an OGG file here encoded as Base64 string."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TranscriptVoiceRequest"
      responses:
        "200":
          description: "Accomplished."
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/TranscriptVoiceResponse"
        "400":
          description: "Error in input data."
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/TranscriptVoiceResponse"
        "404":
          description: "Authorization required."
  /api/v1/command:
    post:
      description: "Execute a voice command"
      operationId: "ExecuteCommand"
      requestBody:
        description: "Provide an OGG file here encoded as Base64 string."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommandRequest"
      responses:
        "200":
          description: "Response on execute a voice command (depends on command type returned)."
          content:
            text/plain:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CommandResponseDice"
                  - $ref: "#/components/schemas/CommandResponseCharacter"
        "400":
          description: "Error in input data."
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/CommandResponse"
        "404":
          description: "Authorization required."
components:
  schemas:
    TranscriptVoiceRequest:
      type: "object"
      properties:
        format:
          type: "string"
          required: true
          enum: [
            "OGG",
          ]
          description: Specify file type.
        file_base64:
          type: "string"
          required: true
          description: File body encoded in Base64 format.
    TranscriptVoiceResponse:
      type: "object"
      properties:
        is_successful:
          type: "boolean"
          required: true
          description: True if AI engine managed to decode file. False - otherwise.
        transcription:
          type: "string"
          required: false
          description: Optional result of voice transcription.
    CommandRequest:
      type: "object"
      properties:
        format:
          type: "string"
          required: true
          enum: [
            "OGG",
          ]
          description: Specify file type.
        file_base64:
          type: "string"
          required: true
          description: File body encoded in Base64 format.
    CommandResponse:
      type: "object"
      properties:
        was_recognized:
          type: "boolean"
          required: true
          description: True if AI engine managed to decode file. False - otherwise.
        transcription:
          type: "string"
          required: false
          description: Optional result of voice transcription.
        commandType:
          type: "string"
          required: false
          description: Command type from recognized command.
          enum: [
            "DICE",
            "CHARACTER",
            "UNKNOWN"
          ]
        commandResult:
          type: "any"
          required: false
          description: Contains command execution results.
    CommandResponseDice:
      type: "object"
      properties:
        was_recognized:
          type: "boolean"
          required: true
          description: True if AI engine managed to decode file. False - otherwise.
        transcription:
          type: "string"
          required: true
          description: Optional result of voice transcription.
        commandType:
          type: "string"
          required: true
          description: Command type from recognized command.
          enum: [
            "DICE"
          ]
        commandResult:
          type: "integer"
          required: true
          description: Contains result of dice role.
    CommandResponseCharacter:
      type: "object"
      properties:
        was_recognized:
          type: "boolean"
          required: true
          description: True if AI engine managed to decode file. False - otherwise.
        transcription:
          type: "string"
          required: true
          description: Optional result of voice transcription.
        commandType:
          type: "string"
          required: true
          description: Command type from recognized command.
          enum: [
            "CHARACTER"
          ]
        commandResult:
          $ref: "#/components/schemas/Character"
    Character:
      type: "object"
      properties:
        description:
          type: "string"
          required: true
          description: Character's description generated by GPT.
        level:
          type: "integer"
          required: true
          description: Character's level.
        strength:
          type: "integer"
          required: true
          description: Character's stats.
        dexterity:
          type: "integer"
          required: true
          description: Character's stats.
        constitution:
          type: "integer"
          required: true
          description: Character's stats.
        intelligence:
          type: "integer"
          required: true
          description: Character's stats.
        wisdom:
          type: "integer"
          required: true
          description: Character's stats.
        charisma:
          type: "integer"
          required: true
          description: Character's stats.