ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
        ai_adapter: Yandex
        is_logging_enabled: true
    deployment:
        # workaround for bug: https://youtrack.jetbrains.com/issue/KTOR-2857
        port: "$G_PORT:12222"